### ISSUE TITLE
HTML Report generation failed

### ISSUE THREAD

**Issue by ayush411** [HLTech/judge-d#136]
below is the response generated from
​/environment-compatibility-report​/{serviceName}:{serviceVersion} endpoint , but generated report coming blank . 
Can you please help on this

[
{
"consumerAndProvider": {
"consumerName": "kyc-consumer",
"consumerVersion": "1.0.1-SNAPSHOT",
"providerName": "kyc-api",
"providerVersion": "1.0.16-SNAPSHOT"
},
"interactions": [
{
"communicationInterface": "rest",
"interactionName": "KYC API - Update Complate flag",
"validationResult": "FAILED",
"errors": [
"Object instance has properties which are not allowed by the schema: ["status"]"
]
}
]
}
]

**Comment by Felipe444** [comment]
Hello,
You have a mismatching schema between a consumer and a provider. All the details are listed under "errors" part of the report:
"Object instance has properties which are not allowed by the schema: ["status"]".
Can you please verify again your schemas?

**Comment by ayush411** [comment]
But python script is not generating above error details into html format. After running py script below is my html coming up.


Pact validation result
Error 
Status: 
Message: 

Path:

**Comment by Felipe444** [comment]
Can you please provide contracts of both consumer and provider? I will try to recreate locally.

**Comment by Felipe444** [comment]
Task to be closed - impossible to recreate.
