### ISSUE TITLE
Ability to get information about the space of the service

### ISSUE THREAD

**Issue by pienikrz** [HLTech/judge-d#159]
**Is your feature request related to a problem? Please describe.**
It is not possible to see spaces that are part of the environment. It's also not possible to determinate space for single service.

**Describe the solution you'd like**
Add information about space to services returned from GET ​/environments​/{name}

**Additional context**
When we provide services for environment (using PUT ​/environments​/{name}) we can use X-JUDGE-D-AGENT-SPACE parameter to set space for services. Unfortunately, this information cannot be read in any way currently.

**Comment by Felipe444** [comment]
done
