### ISSUE TITLE
ValidationController should return proper statuses for not found service or environment

### ISSUE THREAD

**Issue by akolod** [HLTech/judge-d#170]
ACTUAL:
For not found environment, partial data is returned, i.e: 
`{
    "consumerAndProvider": {
      "consumerName": "payments-in",
      "consumerVersion": "1.999.0_e74f358",
      "providerName": "client-data",
      "providerVersion": null
    },
    "interactions": [
      {
        "communicationInterface": "rest",
        "interactionName": "any",
        "validationResult": "FAILED",
        "errors": [
          "provider not available"
        ]
      }
    ]
  }`

For not found service:version for /environment-compatibility-report 400 is returned

EXPECTED:
404 is returned in both cases

Please add test cases to ValidationControllerFT after fix

**Comment by Felipe444** [comment]
Done.
