### ISSUE TITLE
Make POST /contracts instead of POST /contracts/{provider}/{version}

### ISSUE THREAD

**Issue by karolkalinski** [HLTech/judge-d#22]
We want to make our API more RESTful. Therefore we decided to replace POST /contracts with POST /contracts/{provider}/{version}. Both path parameters should be represented in request body. Moreover 409 error must be returned in case when resource already exists (the same provider and version).

**Comment by karolkalinski** [comment]
Starting work on this.

**Comment by Felipe444** [comment]
Rendered obsolete.
